apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: deployment-argocd
  labels:
    app: backend-argocd
spec:
  selector:
    matchLabels:
      app: backend-argocd
  replicas: 3
  template:
    metadata:
      labels:
        app: backend-argocd
    spec:
      containers:
        - name: backend-argocd
          image: crist/argocd-jenkins:27
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: service-argocd
spec:
  selector:
    app: backend-argocd
  type: NodePort
  ports:
    - name: port-message
      protocol: TCP
      port: 8080
